-- =============================================================================
-- Pokémon Price Tracker - Supabase PostgreSQL Schema DDL
-- Target Block: Mega Evolution / Latest Expansions (ligapokemon.com.br)
-- Compatible with PostgreSQL 13+ & Supabase
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- 1. Table: expansions
-- Stores Pokémon card expansion/set metadata.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.expansions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL,
    release_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE public.expansions IS 'Pokémon TCG expansion sets (e.g. Mega Evolution block collections)';
COMMENT ON COLUMN public.expansions.code IS 'Unique code or shorthand key for the expansion (e.g. PRC, ROS, AOR, BKT, BKP, FCO, STS, EVO)';

-- -----------------------------------------------------------------------------
-- 2. Table: cards
-- Stores individual card metadata linked to an expansion.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expansion_id BIGINT NOT NULL REFERENCES public.expansions(id) ON DELETE CASCADE,
    card_number VARCHAR(50) NOT NULL,
    name TEXT NOT NULL,
    rarity TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT unique_expansion_card_number UNIQUE (expansion_id, card_number, name)
);

COMMENT ON TABLE public.cards IS 'Pokémon card catalog entries per expansion';
COMMENT ON COLUMN public.cards.card_number IS 'Collector number in expansion set (e.g. "061/108" or "61/108")';

-- -----------------------------------------------------------------------------
-- 3. Table: price_history
-- Stores historical price snapshots recorded over time for each card.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL REFERENCES public.cards(id) ON DELETE CASCADE,
    price_min NUMERIC(10, 2) NOT NULL CHECK (price_min >= 0),
    price_avg NUMERIC(10, 2) CHECK (price_avg IS NULL OR price_avg >= 0),
    currency VARCHAR(10) DEFAULT 'BRL' NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE public.price_history IS 'TimeSeries price snapshots collected periodically';
COMMENT ON COLUMN public.price_history.price_min IS 'Minimum listing price found in BRL';
COMMENT ON COLUMN public.price_history.price_avg IS 'Average listing price found in BRL';

-- -----------------------------------------------------------------------------
-- Indexes for Optimized Query Performance
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_cards_expansion_id ON public.cards(expansion_id);
CREATE INDEX IF NOT EXISTS idx_cards_name ON public.cards(name);
CREATE INDEX IF NOT EXISTS idx_price_history_card_id ON public.price_history(card_id);
CREATE INDEX IF NOT EXISTS idx_price_history_timestamp ON public.price_history(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_price_history_card_timestamp ON public.price_history(card_id, timestamp DESC);

-- -----------------------------------------------------------------------------
-- Row Level Security (RLS) Configuration
-- -----------------------------------------------------------------------------
ALTER TABLE public.expansions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_history ENABLE ROW LEVEL SECURITY;

-- 1) Public Read Access (Allows front-end static sites to query data)
CREATE POLICY "Allow public read access on expansions"
    ON public.expansions FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Allow public read access on cards"
    ON public.cards FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Allow public read access on price_history"
    ON public.price_history FOR SELECT
    TO anon, authenticated
    USING (true);

-- 2) Write Access for Service Role / Authenticated / Scraper key
CREATE POLICY "Allow write access for authenticated users on expansions"
    ON public.expansions FOR ALL
    TO authenticated, service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow write access for authenticated users on cards"
    ON public.cards FOR ALL
    TO authenticated, service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow write access for authenticated users on price_history"
    ON public.price_history FOR ALL
    TO authenticated, service_role
    USING (true)
    WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- Useful Views for Front-end & Queries
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.latest_card_prices AS
SELECT DISTINCT ON (ph.card_id)
    ph.id AS price_id,
    c.id AS card_id,
    c.name AS card_name,
    c.card_number,
    c.rarity,
    c.image_url,
    e.id AS expansion_id,
    e.name AS expansion_name,
    e.code AS expansion_code,
    ph.price_min,
    ph.price_avg,
    ph.currency,
    ph.timestamp AS price_timestamp
FROM public.price_history ph
JOIN public.cards c ON ph.card_id = c.id
JOIN public.expansions e ON c.expansion_id = e.id
ORDER BY ph.card_id, ph.timestamp DESC;
